#!/usr/bin/env python3
# Safely run ls

import sys
import subprocess

subprocess.check_call(['ls', sys.argv[1]])
